-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.1
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-added-large-files
        args:
        - --maxkb=2000
-   repo: git://github.com/awebdeveloper/pre-commit-tslint/
    sha: ''  # Use the sha or tag you want to point at
    hooks:
    -   id: tslint
        additional_dependencies: ['tslint@5.0.0']
